/** Lesbare Texte für Audit-Ereignisse */
export const AUDIT_LABELS: Record<string, string> = {
  "auth.login": "Anmeldung",
  "team.created": "Team angelegt",
  "key.created": "Key erzeugt",
  "key.imported": "Key importiert",
  "key.deployed": "Key auf Server eingetragen",
  "key.deploy_failed": "Key eintragen fehlgeschlagen",
  "key.revoked_from_server": "Key von Server entfernt",
  "key.revoke_failed": "Key entfernen fehlgeschlagen",
  "key.revoked": "Key gesperrt",
  "key.deleted": "Key gelöscht",
  "key.rotated": "Key rotiert",
  "server.created": "Server hinzugefügt",
  "server.updated": "Server geändert",
  "server.deleted": "Server gelöscht",
  "server.host_key_confirmed": "Fingerprint bestätigt",
  "server.host_key_mismatch": "Host-Key geändert (Warnung)",
  "server.management_key_set": "Verwaltungs-Key geändert",
  "server.user_created": "Linux-Benutzer angelegt",
  "server.user_sudo_configured": "sudo eingerichtet",
  "server.sshd_hardened": "sshd abgesichert",
  "server.ca_installed": "Zertifizierungsstelle installiert",
  "terminal.opened": "Terminal geöffnet",
  "terminal.closed": "Terminal geschlossen",
  "sftp.opened": "Dateibrowser geöffnet",
  "sftp.closed": "Dateibrowser geschlossen",
  "sftp.upload": "Datei hochgeladen",
  "sftp.download": "Datei heruntergeladen",
  "sftp.delete": "Datei gelöscht",
  "sftp.mkdir": "Ordner angelegt",
  "sftp.rename": "Datei umbenannt",
  "member.added": "Mitglied hinzugefügt",
  "member.removed": "Mitglied entfernt",
  "member.role_changed": "Rolle geändert",
  "member.offboarded": "Offboarding ausgeführt",
  "invitation.created": "Einladung verschickt",
  "group.created": "Gruppe angelegt",
  "group.deleted": "Gruppe gelöscht",
  "group.members_changed": "Gruppenmitglieder geändert",
  "server_group.created": "Server-Gruppe angelegt",
  "server_group.deleted": "Server-Gruppe gelöscht",
  "server_group.members_changed": "Server-Gruppe geändert",
  "grant.created": "Freigabe erteilt",
  "grant.deleted": "Freigabe entzogen",
  "team.settings_changed": "Team-Einstellungen geändert",
  "ca.created": "Zertifizierungsstelle angelegt",
  "certificate.issued": "Zertifikat ausgestellt",
  "command.run": "Befehl auf Servern ausgeführt",
  "api_token.created": "API-Token erstellt",
  "api_token.revoked": "API-Token widerrufen",
  "pocket_id.user_disabled": "Pocket-ID-Nutzer gesperrt (Abgleich)",
};

export const auditLabel = (action: string) => AUDIT_LABELS[action] ?? action;
